src/Entity/Admission.php
<?php

namespace App\Entity;

use App\Repository\AdmissionRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AdmissionRepository::class)]
class Admission
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $patient_id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_visit = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $reason = null;

    #[ORM\Column(length: 64)]
    private ?string $bed = null;

    #[ORM\Column(length: 64)]
    private ?string $room = null;

    #[ORM\Column(length: 32)]
    private ?string $status = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPatientId(): ?int
    {
        return $this->patient_id;
    }

    public function setPatientId(int $patient_id): static
    {
        $this->patient_id = $patient_id;

        return $this;
    }

    public function getDateVisit(): ?\DateTimeInterface
    {
        return $this->date_visit;
    }

    public function setDateVisit(\DateTimeInterface $date_visit): static
    {
        $this->date_visit = $date_visit;

        return $this;
    }

    public function getReason(): ?string
    {
        return $this->reason;
    }

    public function setReason(string $reason): static
    {
        $this->reason = $reason;

        return $this;
    }

    public function getBed(): ?string
    {
        return $this->bed;
    }

    public function setBed(string $bed): static
    {
        $this->bed = $bed;

        return $this;
    }

    public function getRoom(): ?string
    {
        return $this->room;
    }

    public function setRoom(string $room): static
    {
        $this->room = $room;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }
}

src/Entity/Patient.php
<?php

namespace App\Entity;

use App\Repository\PatientRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PatientRepository::class)]
class Patient
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_of_birth = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $gender = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $address = null;

    #[ORM\Column(length: 32, nullable: true)]
    private ?string $phone_number = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getDateOfBirth(): ?\DateTimeInterface
    {
        return $this->date_of_birth;
    }

    public function setDateOfBirth(?\DateTimeInterface $date_of_birth): static
    {
        $this->date_of_birth = $date_of_birth;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(?string $gender): static
    {
        $this->gender = $gender;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(?string $phone_number): static
    {
        $this->phone_number = $phone_number;

        return $this;
    }
}

src/Form/PatientType.php
<?php

namespace App\Form;

use App\Entity\Patient;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PatientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('first_name')
            ->add('last_name')
            ->add('date_of_birth')
            ->add('gender')
            ->add('address')
            ->add('phone_number')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Patient::class,
        ]);
    }
}

src/Controller/PatientController.php
<?php
namespace App\Controller;

use App\Entity\Patient;
use App\Entity\Admission;
use App\Form\PatientType;
use App\Repository\PatientRepository;
use App\Repository\AdmissionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\Id;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use function Symfony\Component\String\u;

class PatientController extends AbstractController
{
    #[Route('/patients', name: 'patient_list')]
    public function patient_list(PatientRepository $patientRepository): Response
    {
        $patients = $patientRepository->findAll();
        return $this->render('patient/list.html.twig', [
            'patients' => $patients,
            'notfound' => false,
        ]);
    }

    #[Route('/patients/search', name: 'patient_search')]
    public function patient_search(Request $request, PatientRepository $patientRepository): Response
    {
        $id = $request->get('search');

        if ($id) {
            $patient = $patientRepository->find($id);
            if ($patient) {
                return $this->render('patient/list.html.twig', [
                    'patients' => [$patient],
                    'notfound' => false,
                ]);
            }
            else {
                return $this->render('patient/list.html.twig', [
                    'patients' => $patientRepository->findAll(),
                    'notfound' => true,
                ]);
            }
        }
        else {
            return $this->redirectToRoute('patient_list', ['notfound' => false]);
        }
    }

    #[Route('/patients/create', name: 'patient_create')]
    public function patient_create(Request $request, EntityManagerInterface $entityManager): Response
    {
        $patient = new Patient();

        $form = $this->createForm(PatientType::class, $patient)->add('save', SubmitType::class, [
            'label' => 'Create',
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($patient);
            $entityManager->flush();

            return $this->redirectToRoute('patient_list');
        }

        return $this->render('patient/create.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/patients/{id}', name: 'patient_show')]
    public function patient_show(Patient $patient, AdmissionRepository $admissionRepository): Response
    {
        $admissions = $admissionRepository->findBy(['patient_id' => $patient->getId()], ['date_visit' => 'DESC']);
        return $this->render('patient/show.html.twig', [
            'patient' => $patient,
            'admissions' => $admissions,
        ]);
    }

    #[Route('/patients/{id}/edit', name: 'patient_edit')]
    public function patient_edit(Request $request, Patient $patient, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PatientType::class, $patient)->add('save', SubmitType::class, [
            'label' => 'Update',
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('patient_list');
        }

        return $this->render('patient/edit.html.twig', [
            'form' => $form->createView(),
            'patient' => $patient,
        ]);
    }

    #[Route('/patients/{id}/delete', name: 'patient_delete', methods: ['POST', 'DELETE'])]
    public function patient_delete(Patient $patient, EntityManagerInterface $entityManager): Response
    {
        $entityManager->remove($patient);
        $entityManager->flush();

        return $this->redirectToRoute('patient_list');
    }


}

templates/patient/create.html.twig
 {% extends 'base.html.twig' %}


 {% block body %}
     <main>
         <nav class="breadcrumbs" aria-label="Breadcrumbs">
                <ol>
                    <li><a href="{{ path('home') }}">Home</a></li>
                    <li><a href="{{ path('patient_list') }}" hx-confirm="Are you sure you want to leave?">Patients</a></li>
                    <li aria-current="page">Create</li>
                </ol>
         </nav>
        {{ form(form) }}
     </main>
 {% endblock %}

templates/patient/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <main>
        <nav class="breadcrumbs" aria-label="Breadcrumbs">
            <ol>
                <li><a href="{{ path('home') }}">Home</a></li>
                <li><a href="{{ path('patient_list') }}" hx-confirm="Are you sure you want to leave?">Patients</a></li>
                <li aria-current="page">Edit</li>
            </ol>
        </nav>
        {{ form(form) }}
    </main>
{% endblock %}

templates/patient/list.html.twig
{% extends 'base.html.twig' %}


{% block title %}Patient list{% endblock %}

{% block body %}
    <main>
        <nav class="breadcrumbs" aria-label="Breadcrumbs">
            <ol>
                <li><a href="{{ path('home') }}">Home</a></li>
                <li aria-current="page">Patients</li>
            </ol>
        </nav>
        <h1>Patients</h1>
        <form method="post" action="{{ path('patient_search') }}" style="margin-bottom: 16px">
            <label for="search">Search</label>
            <input type="text" id="search" name="search">
            <button type="submit">Search</button>
        </form>
        {% if notfound %}
            <div class="box bad">
                <strong class="block titlebar">Error</strong>
                No patients found
            </div>
        {% endif %}
        <table class="table">
            <tr>
                <th>Id</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Date of Birth</th>
                <th>Actions</th>
            </tr>
            {% for patient in patients %}
                <tr>
                    <td>{{ patient.id }}</td>
                    <td>{{ patient.firstName }}</td>
                    <td>{{ patient.lastName }}</td>
                    <td>{{ patient.DateOfBirth|date('d-m-Y') }}</td>
                    <td>
                        <a href="{{ path('patient_show', {'id': patient.id}) }}">show</a>
                        <a href="{{ path('patient_edit', {'id': patient.id}) }}">edit</a>
                        <a hx-delete="{{ path('patient_delete', {'id': patient.id}) }}" hx-confirm="Are you sure you want to delete?" hx-target="body">delete</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <button hx-get="{{ path('patient_create') }}" hx-target="body" hx-replace-url="true" hx-push-url="true">Add new patient</button>
        <noscript>
            <a href="{{ path('patient_create') }}">Add new patient</a>
        </noscript>
    </main>
{% endblock %}

templates/patient/show.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    <main>
        <nav class="breadcrumbs" aria-label="Breadcrumbs">
            <ol>
                <li><a href="{{ path('home') }}">Home</a></li>
                <li><a href="{{ path('patient_list') }}">Patients</a></li>
                <li aria-current="page">Details</li>
            </ol>
        </nav>
        <table class="table">
            <tr>
                <th>ID</th>
                <td>{{ patient.Id }}</td>
            </tr>
            <tr>
                <th>First Name</th>
                <td>{{ patient.FirstName }}</td>
            </tr>
            <tr>
                <th>Last Name</th>
                <td>{{ patient.LastName }}</td>
            </tr>
            <tr>
                <th>Date of Birth</th>
                <td>{{ patient.DateOfBirth|date('d-m-Y') }}</td>
            </tr>
            <tr>
                <th>Address</th>
                <td>{{ patient.Address }}</td>
            </tr>
            <tr>
                <th>Phone number</th>
                <td>{{ patient.PhoneNumber }}</td>
            </tr>
        </table>
        <h3>Admission history</h3>
        <table class="table">
            <tr>
                <th>ID</th>
                <th>Date visit</th>
                <th>Status</th>
            </tr>
            {% for admission in admissions %}
                <tr>
                    <td><a href="{{ path('admission_show', {'id': admission.Id}) }}">{{ admission.id }}</a></td>
                    <td>{{ admission.dateVisit|date('d-m-Y') }}</td>
                    <td>{{ admission.status }}</td>
                </tr>
            {% endfor %}
        </table>
    </main>
{% endblock %}