src/Entity/Admission.php
<?php

namespace App\Entity;

use App\Repository\AdmissionRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AdmissionRepository::class)]
class Admission
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $patient_id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_visit = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $reason = null;

    #[ORM\Column(length: 64)]
    private ?string $bed = null;

    #[ORM\Column(length: 64)]
    private ?string $room = null;

    #[ORM\Column(length: 32)]
    private ?string $status = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPatientId(): ?int
    {
        return $this->patient_id;
    }

    public function setPatientId(int $patient_id): static
    {
        $this->patient_id = $patient_id;

        return $this;
    }

    public function getDateVisit(): ?\DateTimeInterface
    {
        return $this->date_visit;
    }

    public function setDateVisit(\DateTimeInterface $date_visit): static
    {
        $this->date_visit = $date_visit;

        return $this;
    }

    public function getReason(): ?string
    {
        return $this->reason;
    }

    public function setReason(string $reason): static
    {
        $this->reason = $reason;

        return $this;
    }

    public function getBed(): ?string
    {
        return $this->bed;
    }

    public function setBed(string $bed): static
    {
        $this->bed = $bed;

        return $this;
    }

    public function getRoom(): ?string
    {
        return $this->room;
    }

    public function setRoom(string $room): static
    {
        $this->room = $room;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }
}

src/Form/AdmissionType.php
<?php

namespace App\Form;

use App\Entity\Admission;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdmissionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('patient_id')
            ->add('date_visit')
            ->add('reason')
            ->add('bed')
            ->add('room')
            ->add('status')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Admission::class,
        ]);
    }
}

src/Controller/AdmissionController.php
<?php
namespace App\Controller;

use App\Entity\Admission;
use App\Entity\Patient;
use App\Form\AdmissionType;
use App\Repository\AdmissionRepository;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AdmissionController extends AbstractController
{
    #[Route('/admissions', name: 'admission_list')]
    public function admission_list(AdmissionRepository $admissionRepository): Response
    {
        $admissions = $admissionRepository->findAll();
        return $this->render('admission/list.html.twig', [
            'admissions' => $admissions,
            'notfound' => false,
        ]);
    }

    #[Route('/admissions/search', name: 'admission_search')]
    public function patient_search(Request $request, AdmissionRepository $admissionRepository): Response
    {
        $id = $request->get('search');

        if ($id) {
            $admission = $admissionRepository->find($id);
            if ($admission) {
                return $this->render('admission/list.html.twig', [
                    'admissions' => [$admission],
                    'notfound' => false,
                ]);
            }
            else {
                return $this->render('admission/list.html.twig', [
                    'admissions' => $admissionRepository->findAll(),
                    'notfound' => true,
                ]);
            }
        }
        else {
            return $this->redirectToRoute('admission_list', ['notfound' => false]);
        }
    }

    #[Route('/admissions/create', name: 'admission_create')]
    public function admission_create(Request $request, EntityManagerInterface $entityManager): Response
    {
        $admission = new Admission();

        $form = $this->createForm(AdmissionType::class, $admission)->add('save', SubmitType::class, [
            'label' => 'Create',
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($admission);
            $entityManager->flush();

            return $this->redirectToRoute('admission_list');
        }

        return $this->render('admission/create.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/admissions/{id}', name: 'admission_show')]
    public function admission_show(Admission $admission): Response
    {
        return $this->render('admission/show.html.twig', [
            'admission' => $admission,
        ]);
    }

    #[Route('/admissions/{id}/edit', name: 'admission_edit')]
    public function admission_edit(Request $request, Admission $admission, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AdmissionType::class, $admission)->add('save', SubmitType::class, [
            'label' => 'Update',
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('admission_list');
        }

        return $this->render('admission/edit.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

templates/admission/create.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    <main>
        <nav class="breadcrumbs" aria-label="Breadcrumbs">
            <ol>
                <li><a href="{{ path('home') }}">Home</a></li>
                <li><a href="{{ path('admission_list') }}" hx-confirm="Are you sure you want to leave?">Admissions</a></li>
                <li aria-current="page">Create</li>
            </ol>
        </nav>
        {{ form(form) }}
    </main>
{% endblock %}

templates/admission/edit.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    <main>
        <nav class="breadcrumbs" aria-label="Breadcrumbs">
            <ol>
                <li><a href="{{ path('home') }}">Home</a></li>
                <li><a href="{{ path('admission_list') }}" hx-confirm="Are you sure you want to leave?">Admissions</a></li>
                <li aria-current="page">Edit</li>
            </ol>
        </nav>
        {{ form(form) }}
    </main>
{% endblock %}

templates/admission/list.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    <main>
        <nav class="breadcrumbs" aria-label="Breadcrumbs">
            <ol>
                <li><a href="{{ path('home') }}">Home</a></li>
                <li aria-current="page">Admissions</li>
            </ol>
        </nav>
        <h1>Admissions</h1>
        <form action="{{ path('admission_search') }}" method="post">
            <label>
                <span>Search By ID</span>
                <input type="text" name="search" placeholder="Search">
            </label>
            <button type="submit">Search</button>
        </form>
        {% if notfound %}
            <div class="box bad">
                <strong class="block titlebar">Error</strong>
                No admissions found
            </div>
        {% endif %}
        <table class="table">
            <tr>
                <th>ID</th>
                <th>Patient ID</th>
                <th>Date visit</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
            {% for admission in admissions %}
                <tr>
                    <td>{{ admission.id }}</td>
                    <td><a href="{{ path('patient_show', {'id': admission.patientId}) }}">{{ admission.patientId }}</a></td>
                    <td>{{ admission.dateVisit|date('d-m-Y') }}</td>
                    <td>{{ admission.status }}</td>
                    <td>
                        <a href="{{ path('admission_show', {'id': admission.patientId}) }}">show</a>
                        <a href="{{ path('admission_edit', {'id': admission.patientId}) }}">edit</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <button hx-get="{{ path('admission_create') }}" hx-target="body" hx-replace-url="true" hx-push-url="true">Add new admission</button>
        <noscript>
            <a href="{{ path('admission_create') }}">Add new addmission</a>
        </noscript>
    </main>
{% endblock %}

templates/admission/show.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    <main>
        <nav class="breadcrumbs" aria-label="Breadcrumbs">
            <ol>
                <li><a href="{{ path('home') }}">Home</a></li>
                <li><a href="{{ path('admission_list') }}">Admission</a></li>
                <li aria-current="page">Details</li>
            </ol>
        </nav>
        <table class="table">
            <tr>
                <th>ID</th>
                <td>{{ admission.Id }}</td>
            </tr>
            <tr>
                <th>Patient ID</th>
                <td><a href="{{ path('patient_show', {'id': admission.patientId}) }}">{{ admission.patientId }}</a></td>
            </tr>
            <tr>
                <th>Date Visited</th>
                <td>{{ admission.dateVisit|date('d-m-Y') }}</td>
            </tr>
            <tr>
                <th>Reason</th>
                <td>{{ admission.reason }}</td>
            </tr>
            <tr>
                <th>Room</th>
                <td>{{ admission.room }}</td>
            </tr>
            <tr>
                <th>Bed</th>
                <td>{{ admission.bed }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ admission.status }}</td>
            </tr>
        </table>
    </main>
{% endblock %}